# Listing of application known JDKs and the URL chunks to use to download them

# [======= Oracle OpenJDK sources =======================================================]
[oracle]
java_home = ""

[oracle.8]
url = "https://download.java.net/openjdk/jdk8u41/ri/openjdk-8u41-b04-linux-x64-14_jan_2020.tar.gz"
filename = "openjdk-8u41-b04-linux-x64-14_jan_2020.tar.gz"

[oracle.11]
url = "https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz"
filename = "openjdk-11+28_linux-x64_bin.tar.gz"

[oracle.15]
url = "https://download.java.net/openjdk/jdk15/ri/openjdk-15+36_linux-x64_bin.tar.gz"
filename = "openjdk-15+36_linux-x64_bin.tar.gz"

# [======= Amazon Corretto JDK sources ==================================================]
[corretto]
java_home = ""

[corretto.8]
url = "https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.tar.gz"
filename = "amazon-corretto-8.265.01.1-linux.x64.tar.gz"

[corretto.11]
url = "https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.tar.gz"
filename = "amazon-corretto-11.0.8.10.1-linux.x64.tar.gz"

# [======= BellSoft Liberica JDK sources (uses the "full" jdk) ==========================]
[liberica]
java_home = ""

[liberica.8]
url = "https://download.bell-sw.com/java/8u265+1/bellsoft-jdk8u265+1-linux-amd64-full.tar.gz"
filename = "bellsoft-jdk8u265+1-linux-amd64-full.tar.gz"

[liberica.11]
url = "https://download.bell-sw.com/java/11.0.8+10/bellsoft-jdk11.0.8+10-linux-amd64-full.tar.gz"
filename = "bellsoft-jdk11.0.8+10-linux-amd64-full.tar.gz"

[liberica.15]
url = "https://download.bell-sw.com/java/15+36/bellsoft-jdk15+36-linux-amd64-full.tar.gz"
filename = "bellsoft-jdk15+36-linux-amd64-full.tar.gz"

# [======= AdoptOpenJDK sources =========================================================]
# syntax = [base_url][ext_url][release_path][tag][filename]
[openjdk]
java_home = ""

[openjdk.8]
url = "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u265-b01/"
filename = "OpenJDK8U-jdk_x64_linux_hotspot_8u265b01.tar.gz"

[openjdk.8.openj9]
url = "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u265-b01_openj9-0.21.0/"
filename = "OpenJDK8U-jre_x64_linux_openj9_8u265b01_openj9-0.21.0.tar.gz"

[openjdk.11]
url = "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/"
tag = "jdk-11.0.8%2B10/"
filename = "OpenJDK11U-jdk_x64_linux_hotspot_11.0.8_10.tar.gz"

[openjdk.11.openj9]
url = "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10_openj9-0.21.0/"
filename = "OpenJDK11U-jdk_x64_linux_openj9_11.0.8_10_openj9-0.21.0.tar.gz"

[openjdk.14]
url = "https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/"
filename = "OpenJDK14U-jdk_x64_linux_hotspot_14.0.2_12.tar.gz"

[openjdk.14.openj9]
url = "https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12_openj9-0.21.0/"
filename = "OpenJDK14U-jdk_x64_linux_openj9_14.0.2_12_openj9-0.21.0.tar.gz"

[openjdk.15]
url = "https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15%2B36/"
filename = "OpenJDK15U-jdk_x64_linux_hotspot_15_36.tar.gz"

# [adoptopenjdk.15.hotspot] # hotspot only available for java 15 adoptopenjdk for now
# [adoptopenjdk.15.openj9]  # unsupported for now
