= jdkenv image:https://img.shields.io/github/workflow/status/aurumcodex/jdkenv/jdkenv-build?style=flat-square[GitHub Workflow Status]

A simple Go program to manage and install (if not found) various JDKs.

Useful for when you use multiple JDK implementations, or want to build on different versions to test your
Java projects or other JVM language projects on different standard libraries.

Creates a directory `.jdkenv` in the `$HOME` directory, and will contain the downloaded JDK .tar.gz archives
fully extracted. Once a JDK has been selected, an `env` file will be created within the `.jdkenv` directory
that can then be sourced via a shell recfile. (`.bashrc`, `.zshrc`, `.profile`, etc.)

Takes quite a lot of inspiration from how JetBrains' IntelliJ IDEA IDE can download and use various JDKs.
(Even the `.toml` files take quite a lot of inspiration from IntelliJ's `*.intellij` files for its known JDKs.)

NOTE: Environment variable setting not yet implemented.

== Dependencies
- Go 1.15 (min version needs to be checked from deps)

== Installation
=== Using Go Modules
- Make sure `$GOBIN` and `$GOPATH` are set, and `$GOBIN` is added to your `$PATH`
- Run `go get -u github.com/aurumcodex/jdkenv`

== Usage
----
Usage:
  jdkenv [flags]
  jdkenv [command]

Available Commands:
  corretto    Set usage of Amazon Corretto JDK
  errors      Print error codes and their meanings
  help        Help about any command
  liberica    Set usage of BellSoft Liberica JDK
  local       Set usage of a locally installed JDK
  openjdk     Set usage of AdoptOpenJDK
  oracle      Set usage of Oracle OpenJDK Reference Implementation
  system      Set usage of system installed JDK

Flags:
  -h, --help       help for jdkenv
  -j, --java int   use specific Java version (valid: 8, 11, 14, 15) (default 8)
      --no-color   use monochrome output
      --spinner    disables the activity spinner (useful for CI or testing) (default true)
----

== Supported JDKs
- Oracle OpenJDK
** JDK 8
** JDK 11
** JDK 15

- Amazon Corretto
** JDK 8
** JDK 11

- BellSoft Liberica
** JDK 8
** JDK 11
** JDK 15

- AdoptOpenJDK
** JDK 8  `(Hotspot JVM / OpenJ9 JVM)`
** JDK 11 `(Hotspot JVM / OpenJ9 JVM)`
** JDK 15 `(Hotspot JVM / OpenJ9 JVM)`

// - SAP Sapmachine
// ** JDK 11
// ** JDK 15

// - Azul Zulu Community™
// ** JDK 8
// ** JDK 11
// ** JDK 15

== License
JDKEnv is licensed under the Apache 2.0 License.
See link:LICENSE[LICENSE] for more details.