[sapmachine]
vendor    = "SAP"
product   = "Sapmachine"
jdk_major = 11
version   = "11.0.8"

# matching `os` and `arch` keys to golang's runtime GOOS and GOARCH values
[sapmachine.windows]
os        = "windows"
arch      = "amd64"
url       = "https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.8/sapmachine-jdk-11.0.8_windows-x64_bin.zip"
filename  = "sapmachine-jdk-11.0.8_windows-x64_bin.zip"
sha256    = "19ed73a3bc2a1f8e1fc2409f4e3c1fba9ef93d43ec267cb9ebcfaa5f0f43e3c8"
java_home_prefix = ""

[sapmachine.macos]
os        = "darwin"
arch      = "amd64"
url       = "https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.8/sapmachine-jdk-11.0.8_osx-x64_bin.tar.gz"
filename  = "sapmachine-jdk-11.0.8_osx-x64_bin.tar.gz"
sha256    = "6935a166231deb6357e83cf6b0be214b06d05a73415bfda45f367c0eec9edc55"
java_home_prefix = "Contents/Home"

[sapmachine.linux]
os        = "linux"
arch      = "amd64"
url       = "https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.8/sapmachine-jdk-11.0.8_linux-x64_bin.tar.gz"
filename  = "sapmachine-jdk-11.0.8_linux-x64_bin.tar.gz"
sha256    = "fb0a39e18ab893da6a27a0b7f09f52b0b049503205d4d1c29a2228cb16372539"
java_home_prefix = ""