[adopt-openjdk]
vendor    = "AdoptOpenJDK"
flavor    = "Hotspot"
jdk_major = 8
version   = "8u265-b01"

# matching `os` and `arch` keys to golang's runtime GOOS and GOARCH values
[adopt-openjdk.windows]
os        = "windows"
arch      = "amd64"
url       = "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u265-b01/OpenJDK8U-jdk_x64_windows_hotspot_8u265b01.zip"
filename  = "OpenJDK8U-jdk_x64_windows_hotspot_8u265b01.zip"
sha256    = "d0e14e27753f1152643b4ee6f2c57dafbf5641e61ffe93deb56e0701bc3f84c6"
java_home_prefix = ""

[adopt-openjdk.macos]
os        = "darwin"
arch      = "amd64"
url       = "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u265-b01/OpenJDK8U-jdk_x64_mac_hotspot_8u265b01.tar.gz"
filename  = "OpenJDK8U-jdk_x64_mac_hotspot_8u265b01.tar.gz"
sha256    = "f316b154e8c4a99b95bc3d07add3c9b19609c541a2f297112f274c1abce1efb4"
java_home_prefix = "Contents/Home"

[adopt-openjdk.linux]
os        = "linux"
arch      = "amd64"
url       = "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u265-b01/OpenJDK8U-jdk_x64_linux_hotspot_8u265b01.tar.gz"
filename  = "OpenJDK8U-jdk_x64_linux_hotspot_8u265b01.tar.gz"
sha256    = "1285da6278f2d38a790a21148d7e683f20de0799c44b937043830ef6b57f58c4"
java_home_prefix = ""