[azul]
vendor    = "Azul"
product   = "Zulu Community"
jdk_major = 11
version   = "11.0.8"

# matching `os` and `arch` keys to golang's runtime GOOS and GOARCH values
[azul.windows]
os        = "windows"
arch      = "amd64"
url       = "https://cdn.azul.com/zulu/bin/zulu11.41.23-ca-jdk11.0.8-win_x64.zip"
filename  = "zulu11.41.23-ca-jdk11.0.8-win_x64.zip"
sha256    = "3602ed7bae52898c540c2d3ae3230c081cf061b219d14fb9ac15a47f4226d307"
java_home_prefix = ""

[azul.macos]
os        = "darwin"
arch      = "amd64"
url       = "https://cdn.azul.com/zulu/bin/zulu11.41.23-ca-jdk11.0.8-macosx_x64.tar.gz"
filename  = "zulu11.41.23-ca-jdk11.0.8-macosx_x64.tar.gz"
sha256    = "1ed070ea9a27030bcca4d7c074dec1d205d3f3506166d36faf4d1b9e083ab365"
java_home_prefix = "Contents/Home"

[azul.linux]
os        = "linux"
arch      = "amd64"
url       = "https://cdn.azul.com/zulu/bin/zulu11.41.23-ca-jdk11.0.8-linux_x64.tar.gz"
filename  = "zulu11.41.23-ca-jdk11.0.8-linux_x64.tar.gz"
sha256    = "f8aee4ab30ca11ab3c8f401477df0e455a9d6b06f2710b2d1b1ddcf06067bc79"
java_home_prefix = ""