[azul]
vendor    = "Azul"
product   = "Zulu Community"
jdk_major = 8
version   = "1.8.0_265"

# matching `os` and `arch` keys to golang's runtime GOOS and GOARCH values
[azul.windows]
os        = "windows"
arch      = "amd64"
url       = "https://cdn.azul.com/zulu/bin/zulu8.48.0.53-ca-jdk8.0.265-win_x64.zip"
filename  = "zulu8.48.0.53-ca-jdk8.0.265-win_x64.zip"
sha256    = "ba8036b8080549f1e575d9f3f68708e6612404b4a55d474918cef7a14778595a"
java_home_prefix = ""

[azul.macos]
os        = "darwin"
arch      = "amd64"
url       = "https://cdn.azul.com/zulu/bin/zulu8.48.0.53-ca-jdk8.0.265-macosx_x64.tar.gz"
filename  = "zulu8.48.0.53-ca-jdk8.0.265-macosx_x64.tar.gz"
sha256    = "1e981dc2b1c3b3d228e32825e59912e073a9ac47d257c8a0a7e182888feb4b0c"
java_home_prefix = "Contents/Home"

[azul.linux]
os        = "linux"
arch      = "amd64"
url       = "https://cdn.azul.com/zulu/bin/zulu8.48.0.53-ca-jdk8.0.265-linux_x64.tar.gz"
filename  = "zulu8.48.0.53-ca-jdk8.0.265-linux_x64.tar.gz"
sha256    = "ed32513524b32a83b3b388831c69d1884df5675bd5069c6d1485fd1a060be209"
java_home_prefix = ""