[azul]
vendor    = "Azul"
product   = "Zulu Community"
jdk_major = 15
version   = "15.27+17"

# matching `os` and `arch` keys to golang's runtime GOOS and GOARCH values
[azul.windows]
os        = "windows"
arch      = "amd64"
url       = "https://cdn.azul.com/zulu/bin/zulu15.27.17-ca-jdk15.0.0-win_x64.zip"
filename  = "zulu15.27.17-ca-jdk15.0.0-win_x64.zip"
sha256    = "f535a530151e6c20de8a3078057e332b08887cb3ba1a4735717357e72765cad6"
java_home_prefix = ""

[azul.macos]
os        = "darwin"
arch      = "amd64"
url       = "https://cdn.azul.com/zulu/bin/zulu15.27.17-ca-jdk15.0.0-macosx_x64.tar.gz"
filename  = "zulu15.27.17-ca-jdk15.0.0-macosx_x64.tar.gz"
sha256    = "f80b2e0512d9d8a92be24497334c974bfecc8c898fc215ce0e76594f00437482"
java_home_prefix = "Contents/Home"

[azul.linux]
os        = "linux"
arch      = "amd64"
url       = "https://cdn.azul.com/zulu/bin/zulu15.27.17-ca-jdk15.0.0-linux_x64.tar.gz"
filename  = "zulu15.27.17-ca-jdk15.0.0-linux_x64.tar.gz"
sha256    = "0a38f1138c15a4f243b75eb82f8ef40855afcc402e3c2a6de97ce8235011b1ad"
java_home_prefix = ""