name: jdkenv-build
on: [push]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - name: test application
        id: test
        run: bash actions.sh
      - uses: actions/upload-artifact@v2
        with:
          name: jdkenv-bin
          path: |
            ./jdkenv
            ./jdk_list.toml
            ./config.ini
            ./README.adoc
            ./LICENSE